# Generated by Django 5.0.3 on 2024-03-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_site', '0003_alter_commentlike_comment_alter_postlike_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(to='social_media_site.profile'),
        ),
    ]
