# Generated by Django 5.0.3 on 2024-03-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_site', '0004_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/post_photos/%Y/%m/%d/'),
        ),
    ]
