# Generated by Django 5.0.3 on 2024-07-29 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='admins',
            field=models.ManyToManyField(related_name='admin_group_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
