# Generated by Django 5.0.3 on 2024-07-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_groupchat_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='group_image',
            field=models.ImageField(blank=True, upload_to='chat/images/%Y/%m/%d/'),
        ),
    ]
