# Generated by Django 5.0.3 on 2024-10-20 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_groupchat_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_group_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
